name: flutter_reference_template
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  json_serializable:
  riverpod_annotation:
  shared_preferences:
  simple_logger:

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed:
  pedantic_mono:
  riverpod_generator:

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
